### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by newburns** [lbdc/zm_movie_bootstrap#1]
Guess this is not working with PHP 7 using the remi repo.
No cameras show in the camera drop down, and there are no errors present in the httpd/error_log.

CentOS Linux release 7.2.1511 (Core)

Zoneminder 1.29.0

php -v
PHP 7.0.7 (cli) (built: May 25 2016 18:28:00) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by lbdc** [comment]
Fix tested on Ubuntu 16.04
