### ISSUE TITLE
Video Size Calculation

### ISSUE THREAD

**Issue by newburns** [lbdc/zm_movie_bootstrap#2]
The video size is giving a default set of resolutions, however, the actual 704x480 camera size is not available.
This causes an issue as 640x480 is the only resolution to work with this camera size.

**Comment by lbdc** [comment]
For all video sizes, the script calculates aspect ratio. In this case it will be "scale=704:-1"

**Comment by lbdc** [comment]
Why the fork?

**Comment by newburns** [comment]
To correct and add additional sizes
