### ISSUE TITLE
Undefined Function call in PHP 5.6

### ISSUE THREAD

**Issue by newburns** [lbdc/zm_movie_bootstrap#3]
`Undefined variable: function_call in /var/www/html/zm_movie_functions.php on line 191`
This shows up in my ssl_error_log whenever I try to create a video.
I'm using:
`php -v
PHP 5.6.31 (cli) (built: Jul  6 2017 08:06:11)

cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

ZoneMinder Console - Running - default v1.30.4`

**Comment by newburns** [comment]
I see the call in
`zm_movie_make.php
line 29  $camera = Load_Camera();`

It has the correct name and spelling as the zm_movie_function.php
I'm not sure why the function_call is undefined. It is defined at the beginning of the function file. Is there something that I'm missing in PHP or PHP extension?

**Comment by lbdc** [comment]
A few question:
1) Did you do an upgrade recently (PHP)
2) Are you calling the script from the button on index page "zm_movie_list.php"

Internet was down for a while. I'll look into it this shortly

**Comment by lbdc** [comment]
Showed up as a warning on my system when the script was loaded without any parameters. Fixed by initializing variable. Let me know if you are still having problems.
