### ISSUE TITLE
Nothing starts

### ISSUE THREAD

**Issue by newburns** [lbdc/zm_movie_bootstrap#4]
Not sure what the problem is.
I create a video and there are no errors present in
/var/log/httpd/error_log
/var/log/httpd/ssl_error_log
/var/log/messages

My versions are:
CentOS Linux release 7.3.1611 (Core)

PHP 7.0.23 (cli) (built: Aug 29 2017 17:27:07) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

You are running the most recent version of ZoneMinder, v1.30.4.

Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28

Nothing runs according to htop or zm_movie_list.php
Using latest master without any modifications

**Comment by newburns** [comment]
Forgot ffmpeg

ffmpeg version 2.8.12 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-11)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100

**Comment by lbdc** [comment]
Few questions
Was it running since the latest closed issue "Undefined Function call in PHP 5.6"?
Did you verify if files were actually created in the listed in folder zm_movie_path.txt
Any log in apache.log

**Comment by newburns** [comment]
It did not run after the Undefined Function call in PHP 5.6
The error went away, but there was no additional errors.
Apache HTTP 2.4 on CentOS 7 writes logs to /var/log/httpd/error_log and ./ssl_error_log
Neither have additional errors.

Also, systemctl displays the last 5 logs and it didn't show anything in
systemctl status httpd.

**Comment by newburns** [comment]
No files were written to zm_movie_path.txt
It is readable by apache. Even when set as `chmod 777`
Also, this system was running just fine until updates. Not sure which update killed it.
Uninstalled, and reinstalled php7.0 and Zoneminder. That did not fix it.

**Comment by lbdc** [comment]
Just installed a fresh version of centos 7/zoneminder/zm_movie_bootstrap and everything works

Ensure that the folder name listed in zm_movie_path.txt exists (defaults to zm_movie or in this case  /var/www/html/zm_movie and that apache has write permission

**Comment by newburns** [comment]
So...
turns out that my hardware systems have "policycoreutils-gui" installed as part of our deployment.
This in turns installs 
```
libbluray                            x86_64               0.2.3-5.el7
gnome-python2-bonobo                 x86_64               2.28.1-14.el7
gnome-python2-gnome                  x86_64               2.28.1-14.el7
gnome-python2-gnomevfs               x86_64               2.28.1-14.el7
gnome-vfs2                           x86_64               2.24.4-14.el7
gvfs                                 x86_64               1.22.4-8.el7
libbonoboui                          x86_64               2.24.5-7.el7
libgnome                             x86_64               2.32.1-9.el7
libgnomeui                           x86_64               2.24.5-8.el7
policycoreutils-gui
```
Also, I'm not sure where it comes from, but I had 2 versions of x264-libs installed. Must have been from a zmrepo update.
```
x264-libs-0.148-11.20160614gita5e06b9.el7.x86_64
x264-libs-0.148-5.20160118git5c65704.el7.centos.x86_64
```
I removed 
```
yum remove x264-libs-0.148-5* libbluray
```

That solved everything.
That was some awful troubleshooting. Nothing was present in the logs. Do you know what went wrong?

**Comment by lbdc** [comment]
It was the SELINUX that created the problem, preventing files to be written to the movie folder including any log files. Any x264 libs issue would have showed up after creating the list and log files
