### ISSUE TITLE
Speed Number does not change

### ISSUE THREAD

**Issue by newburns** [lbdc/zm_movie_bootstrap#5]
I tried setting the speed to 1, but it produces video at 10x no matter what.
Each of my 8 hour videos produce a 58 minute .mp4

**Comment by lbdc** [comment]
The settings "Maxtime" is set to 60 minutes so the script will automatically adjust the movie speed so that it's length do not exceed it.

If you set Maxtime to 0 it will disable the maximum movie time parameter. Please test it (I never made a video larger than one hour)
